name: Update Top LLM Leaderboard

on:
  # Ce cron s'exécute tous les jours à 03:00 UTC.
  schedule:
    - cron: '0 3 * * *'
  # Permet un déclenchement manuel
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    # Les permissions sont nécessaires pour que l'action puisse pousser du code
    permissions:
      contents: write

    steps:
      # 1. Récupère le code du dépôt (branche main)
      - name: Checkout main branch
        uses: actions/checkout@v4

      # 2. Met en place l'environnement Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # 3. Installe SEULEMENT les dépendances nécessaires
      - name: Install dependencies
        run: pip install pandas requests beautifulsoup4

      # 4. Exécute le script Python
      - name: Run script to generate files
        run: python extract_leaderboard.py 

      # 5. Valide et pousse les changements sur la branche 'main'
      - name: Commit and push to main
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          # 1. On stage TOUS les nouveaux/modified fichiers
          git add top_llms.md top_llms.json
          # 2. On teste si l'index diffère de HEAD
          if git diff --cached --quiet; then
            echo "✅ No changes to commit."
          else
            git commit -m "update: leaderboard top ${TOP_N}s [auto]"
            git push
            echo "🚀 Changes committed and pushed to main."
          fi


      # 6. Crée un dossier temporaire pour le site et copie les fichiers nécessaires
      - name: Prepare site
        run: |
          mkdir site
          cp top_llms.md site/index.md
          # AJOUT IMPORTANT : Copie le fichier de configuration dans le dossier du site.
          # Sans cette ligne, GitHub Pages ne peut pas trouver la configuration pour le titre.
          if [ -f _config.yml ]; then
            cp _config.yml site/
          fi
          # Copie le dossier des 'includes' s'il existe
          if [ -d _includes ]; then
            cp -r _includes site/
          fi

      # 7. Publie le résultat sur GitHub Pages (branche gh-pages)
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
          publish_branch: gh-pages
          enable_jekyll: true 
