name: Update Top LLM Leaderboard

on:
  schedule:
    - cron: '0 3 * * *'   # tous les jours à 03:00 UTC
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas requests beautifulsoup4

      - name: Run script to generate files
        run: python extract_leaderboard.py

      - name: Commit and push to main (robuste)
        run: |
          set -euo pipefail
          git config --global user
